services:
  server:
    image: node:latest
    working_dir: /app
    command: bash -c "cd ./database && node initdb.js && cd .. && npm install && npm run dev" 
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:r
      - ./data:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=abeille
    

  